### ISSUE TITLE
No link available on the menu for the settings

### ISSUE THREAD

**Issue by chunkang** [samuellawrentz/jira-git-commit-helper#1]
How do I set my Jira server URL? I can't find any link to the settings in VSCode 1.18.1

**Comment by samuellawrentz** [comment]
Hi.. Thanks for using this ext.
Sorry for the inconvenience. Yes, I'm working on a fix for that.

Right now you can do 3 steps
1. cmd/ctrl + Shift + P and run the "JIRA Commit Message: Reset Username & Token"
2. Disable and Enable Extension again.
3. Run the "JIRA Commit Message: Create commit message" command again.

It will prompt you for the URL and token.

Will update you once the fix is released.

**Comment by samuellawrentz** [comment]
Have released a new version. Closing this for now. Please let me know if the issue persists.
